# Generated by Django 4.2.19 on 2025-03-01 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('passport_id', models.CharField(blank=True, max_length=255, null=True)),
                ('iin', models.CharField(blank=True, max_length=255, null=True)),
                ('edrpou', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rate', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('code', models.CharField(max_length=255)),
                ('invoice_file_path', models.CharField(max_length=255)),
                ('commission', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('pdv', models.IntegerField()),
                ('commission_amount_no_pdv', models.DecimalField(decimal_places=2, max_digits=19)),
                ('services_total_no_pdv', models.DecimalField(decimal_places=2, max_digits=19)),
                ('total_no_pdv', models.DecimalField(decimal_places=2, max_digits=19)),
                ('total_pdv', models.DecimalField(decimal_places=2, max_digits=19)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RealAgency.client')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='ProvidedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('pdv', models.IntegerField()),
                ('total_no_pdv', models.DecimalField(decimal_places=2, max_digits=19)),
                ('total_pdv', models.DecimalField(decimal_places=2, max_digits=19)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RealAgency.invoice')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RealAgency.service')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RealAgency.discount')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RealAgency.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RealAgency.clienttype'),
        ),
    ]
